// <auto-generated />
namespace MedicalSystem.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FluentApiconfigurationrefactoring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FluentApiconfigurationrefactoring));
        
        string IMigrationMetadata.Id
        {
            get { return "201706081518394_Fluent Api configuration refactoring"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
